/*
  File autogenerated by gengetopt version 2.23
  generated with the following command:
  gengetopt -i options.ggo 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "cmdline.h"

const char *gengetopt_args_info_purpose = "";

const char *gengetopt_args_info_usage = "Usage: mapptth [OPTION]...";

const char *gengetopt_args_info_versiontext = "";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_help[] = {
  "  -h, --help                    Print help and exit",
  "  -V, --version                 Print version and exit",
  "  -t, --threads=INT             Number of threads.  (default=`5')",
  "  -u, --url=STRING              URL of where to start.",
  "  -m, --timeout=INT             Timeout in seconds.  (default=`3')",
  "  -D, --max-depth=INT           Maximum depth of paths.",
  "  -s, --allow-subdomains        Allow the crawler to go to URLs found on a\n                                  sub-domain.  (default=off)",
  "  -a, --allowed-domains=STRING  Allow the crawler to go to URLs found on other\n                                  domains.",
  "  -d, --disallowed-paths=STRING Disallow the crawler to go to these\n                                  directories.",
  "  -x, --allowed-extensions=STRING\n                                The crawler will only fetch documents with\n                                  these extensions, but if no extension is\n                                  found in an URL, this filter won't apply.\n                                  Extensions have to start with a '.' (dot).",
  "  -k, --keep-query              Keep the query part in the URL.  (default=off)",
  "  -c, --no-color                Don't use color when outputing on the console.\n                                  (default=off)",
  "  -U, --user-agent=STRING       Set the user-agent string. You can not send the\n                                  user-agent header by giving an empty string.",
  "  -T, --title                   Print title if there is one.  (default=off)",
  "  -S, --sitemap=STRING          URL of the sitemap.",
  "\n Group: scheme",
  "  -p, --http-only               Only fetch URLs with HTTP as scheme.",
  "  -P, --https-only              Only fetch URLs with HTTPS as scheme.",
  "\n Group: parsing-part",
  "  -B, --only-body               Only parse the <body>.",
  "  -H, --only-head               Only parse the <head>.",
  "\n Group: resolving-ip-version",
  "  -6, --IPv6                    Only resolve to IPv6 addresses.",
  "  -4, --IPv4                    Only resolve to IPv4 addresses.",
    0
};

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
  , ARG_INT
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->threads_given = 0 ;
  args_info->url_given = 0 ;
  args_info->timeout_given = 0 ;
  args_info->max_depth_given = 0 ;
  args_info->allow_subdomains_given = 0 ;
  args_info->allowed_domains_given = 0 ;
  args_info->disallowed_paths_given = 0 ;
  args_info->allowed_extensions_given = 0 ;
  args_info->keep_query_given = 0 ;
  args_info->no_color_given = 0 ;
  args_info->user_agent_given = 0 ;
  args_info->title_given = 0 ;
  args_info->sitemap_given = 0 ;
  args_info->http_only_given = 0 ;
  args_info->https_only_given = 0 ;
  args_info->only_body_given = 0 ;
  args_info->only_head_given = 0 ;
  args_info->IPv6_given = 0 ;
  args_info->IPv4_given = 0 ;
  args_info->parsing_part_group_counter = 0 ;
  args_info->resolving_ip_version_group_counter = 0 ;
  args_info->scheme_group_counter = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->threads_arg = 5;
  args_info->threads_orig = NULL;
  args_info->url_arg = NULL;
  args_info->url_orig = NULL;
  args_info->timeout_arg = 3;
  args_info->timeout_orig = NULL;
  args_info->max_depth_orig = NULL;
  args_info->allow_subdomains_flag = 0;
  args_info->allowed_domains_arg = NULL;
  args_info->allowed_domains_orig = NULL;
  args_info->disallowed_paths_arg = NULL;
  args_info->disallowed_paths_orig = NULL;
  args_info->allowed_extensions_arg = NULL;
  args_info->allowed_extensions_orig = NULL;
  args_info->keep_query_flag = 0;
  args_info->no_color_flag = 0;
  args_info->user_agent_arg = NULL;
  args_info->user_agent_orig = NULL;
  args_info->title_flag = 0;
  args_info->sitemap_arg = NULL;
  args_info->sitemap_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->threads_help = gengetopt_args_info_help[2] ;
  args_info->url_help = gengetopt_args_info_help[3] ;
  args_info->timeout_help = gengetopt_args_info_help[4] ;
  args_info->max_depth_help = gengetopt_args_info_help[5] ;
  args_info->allow_subdomains_help = gengetopt_args_info_help[6] ;
  args_info->allowed_domains_help = gengetopt_args_info_help[7] ;
  args_info->allowed_domains_min = 0;
  args_info->allowed_domains_max = 0;
  args_info->disallowed_paths_help = gengetopt_args_info_help[8] ;
  args_info->disallowed_paths_min = 0;
  args_info->disallowed_paths_max = 0;
  args_info->allowed_extensions_help = gengetopt_args_info_help[9] ;
  args_info->allowed_extensions_min = 0;
  args_info->allowed_extensions_max = 0;
  args_info->keep_query_help = gengetopt_args_info_help[10] ;
  args_info->no_color_help = gengetopt_args_info_help[11] ;
  args_info->user_agent_help = gengetopt_args_info_help[12] ;
  args_info->title_help = gengetopt_args_info_help[13] ;
  args_info->sitemap_help = gengetopt_args_info_help[14] ;
  args_info->http_only_help = gengetopt_args_info_help[16] ;
  args_info->https_only_help = gengetopt_args_info_help[17] ;
  args_info->only_body_help = gengetopt_args_info_help[19] ;
  args_info->only_head_help = gengetopt_args_info_help[20] ;
  args_info->IPv6_help = gengetopt_args_info_help[22] ;
  args_info->IPv4_help = gengetopt_args_info_help[23] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);

  if (strlen(gengetopt_args_info_versiontext) > 0)
    printf("\n%s\n", gengetopt_args_info_versiontext);
}

static void print_help_common(void)
{
	size_t len_purpose = strlen(gengetopt_args_info_purpose);
	size_t len_usage = strlen(gengetopt_args_info_usage);

	if (len_usage > 0) {
		printf("%s\n", gengetopt_args_info_usage);
	}
	if (len_purpose > 0) {
		printf("%s\n", gengetopt_args_info_purpose);
	}

	if (len_usage || len_purpose) {
		printf("\n");
	}

	if (strlen(gengetopt_args_info_description) > 0) {
		printf("%s\n\n", gengetopt_args_info_description);
	}
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}

/** @brief generic value variable */
union generic_value {
    int int_arg;
    char *string_arg;
    const char *default_string_arg;
};

/** @brief holds temporary values for multiple options */
struct generic_list
{
  union generic_value arg;
  char *orig;
  struct generic_list *next;
};

/**
 * @brief add a node at the head of the list 
 */
static void add_node(struct generic_list **list) {
  struct generic_list *new_node = (struct generic_list *) malloc (sizeof (struct generic_list));
  new_node->next = *list;
  *list = new_node;
  new_node->arg.string_arg = 0;
  new_node->orig = 0;
}


static void
free_multiple_string_field(unsigned int len, char ***arg, char ***orig)
{
  unsigned int i;
  if (*arg) {
    for (i = 0; i < len; ++i)
      {
        free_string_field(&((*arg)[i]));
        free_string_field(&((*orig)[i]));
      }
    free_string_field(&((*arg)[0])); /* free default string */

    free (*arg);
    *arg = 0;
    free (*orig);
    *orig = 0;
  }
}

static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{

  free_string_field (&(args_info->threads_orig));
  free_string_field (&(args_info->url_arg));
  free_string_field (&(args_info->url_orig));
  free_string_field (&(args_info->timeout_orig));
  free_string_field (&(args_info->max_depth_orig));
  free_multiple_string_field (args_info->allowed_domains_given, &(args_info->allowed_domains_arg), &(args_info->allowed_domains_orig));
  free_multiple_string_field (args_info->disallowed_paths_given, &(args_info->disallowed_paths_arg), &(args_info->disallowed_paths_orig));
  free_multiple_string_field (args_info->allowed_extensions_given, &(args_info->allowed_extensions_arg), &(args_info->allowed_extensions_orig));
  free_string_field (&(args_info->user_agent_arg));
  free_string_field (&(args_info->user_agent_orig));
  free_string_field (&(args_info->sitemap_arg));
  free_string_field (&(args_info->sitemap_orig));
  
  

  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  FIX_UNUSED (values);
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}

static void
write_multiple_into_file(FILE *outfile, int len, const char *opt, char **arg, const char *values[])
{
  int i;
  
  for (i = 0; i < len; ++i)
    write_into_file(outfile, opt, (arg ? arg[i] : 0), values);
}

int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->threads_given)
    write_into_file(outfile, "threads", args_info->threads_orig, 0);
  if (args_info->url_given)
    write_into_file(outfile, "url", args_info->url_orig, 0);
  if (args_info->timeout_given)
    write_into_file(outfile, "timeout", args_info->timeout_orig, 0);
  if (args_info->max_depth_given)
    write_into_file(outfile, "max-depth", args_info->max_depth_orig, 0);
  if (args_info->allow_subdomains_given)
    write_into_file(outfile, "allow-subdomains", 0, 0 );
  write_multiple_into_file(outfile, args_info->allowed_domains_given, "allowed-domains", args_info->allowed_domains_orig, 0);
  write_multiple_into_file(outfile, args_info->disallowed_paths_given, "disallowed-paths", args_info->disallowed_paths_orig, 0);
  write_multiple_into_file(outfile, args_info->allowed_extensions_given, "allowed-extensions", args_info->allowed_extensions_orig, 0);
  if (args_info->keep_query_given)
    write_into_file(outfile, "keep-query", 0, 0 );
  if (args_info->no_color_given)
    write_into_file(outfile, "no-color", 0, 0 );
  if (args_info->user_agent_given)
    write_into_file(outfile, "user-agent", args_info->user_agent_orig, 0);
  if (args_info->title_given)
    write_into_file(outfile, "title", 0, 0 );
  if (args_info->sitemap_given)
    write_into_file(outfile, "sitemap", args_info->sitemap_orig, 0);
  if (args_info->http_only_given)
    write_into_file(outfile, "http-only", 0, 0 );
  if (args_info->https_only_given)
    write_into_file(outfile, "https-only", 0, 0 );
  if (args_info->only_body_given)
    write_into_file(outfile, "only-body", 0, 0 );
  if (args_info->only_head_given)
    write_into_file(outfile, "only-head", 0, 0 );
  if (args_info->IPv6_given)
    write_into_file(outfile, "IPv6", 0, 0 );
  if (args_info->IPv4_given)
    write_into_file(outfile, "IPv4", 0, 0 );
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

static char *
get_multiple_arg_token(const char *arg)
{
  const char *tok;
  char *ret;
  size_t len, num_of_escape, i, j;

  if (!arg)
    return 0;

  tok = strchr (arg, ',');
  num_of_escape = 0;

  /* make sure it is not escaped */
  while (tok)
    {
      if (*(tok-1) == '\\')
        {
          /* find the next one */
          tok = strchr (tok+1, ',');
          ++num_of_escape;
        }
      else
        break;
    }

  if (tok)
    len = (size_t)(tok - arg + 1);
  else
    len = strlen (arg) + 1;

  len -= num_of_escape;

  ret = (char *) malloc (len);

  i = 0;
  j = 0;
  while (arg[i] && (j < len-1))
    {
      if (arg[i] == '\\' && 
	  arg[ i + 1 ] && 
	  arg[ i + 1 ] == ',')
        ++i;

      ret[j++] = arg[i++];
    }

  ret[len-1] = '\0';

  return ret;
}

static const char *
get_multiple_arg_token_next(const char *arg)
{
  const char *tok;

  if (!arg)
    return 0;

  tok = strchr (arg, ',');

  /* make sure it is not escaped */
  while (tok)
    {
      if (*(tok-1) == '\\')
        {
          /* find the next one */
          tok = strchr (tok+1, ',');
        }
      else
        break;
    }

  if (! tok || strlen(tok) == 1)
    return 0;

  return tok+1;
}

static int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, unsigned int min, unsigned int max, const char *option_desc);

int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, unsigned int min, unsigned int max, const char *option_desc)
{
  int error_occurred = 0;

  if (option_given && (min > 0 || max > 0))
    {
      if (min > 0 && max > 0)
        {
          if (min == max)
            {
              /* specific occurrences */
              if (option_given != (unsigned int) min)
                {
                  fprintf (stderr, "%s: %s option occurrences must be %d\n",
                    prog_name, option_desc, min);
                  error_occurred = 1;
                }
            }
          else if (option_given < (unsigned int) min
                || option_given > (unsigned int) max)
            {
              /* range occurrences */
              fprintf (stderr, "%s: %s option occurrences must be between %d and %d\n",
                prog_name, option_desc, min, max);
              error_occurred = 1;
            }
        }
      else if (min > 0)
        {
          /* at least check */
          if (option_given < min)
            {
              fprintf (stderr, "%s: %s option occurrences must be at least %d\n",
                prog_name, option_desc, min);
              error_occurred = 1;
            }
        }
      else if (max > 0)
        {
          /* at most check */
          if (option_given > max)
            {
              fprintf (stderr, "%s: %s option occurrences must be at most %d\n",
                prog_name, option_desc, max);
              error_occurred = 1;
            }
        }
    }
    
  return error_occurred;
}
static void
reset_group_parsing_part(struct gengetopt_args_info *args_info)
{
  if (! args_info->parsing_part_group_counter)
    return;
  
  args_info->only_body_given = 0 ;
  args_info->only_head_given = 0 ;

  args_info->parsing_part_group_counter = 0;
}

static void
reset_group_resolving_ip_version(struct gengetopt_args_info *args_info)
{
  if (! args_info->resolving_ip_version_group_counter)
    return;
  
  args_info->IPv6_given = 0 ;
  args_info->IPv4_given = 0 ;

  args_info->resolving_ip_version_group_counter = 0;
}

static void
reset_group_scheme(struct gengetopt_args_info *args_info)
{
  if (! args_info->scheme_group_counter)
    return;
  
  args_info->http_only_given = 0 ;
  args_info->https_only_given = 0 ;

  args_info->scheme_group_counter = 0;
}

int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error_occurred = 0;
  FIX_UNUSED (additional_error);

  /* checks for required options */
  if (! args_info->url_given)
    {
      fprintf (stderr, "%s: '--url' ('-u') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  
  if (check_multiple_option_occurrences(prog_name, args_info->allowed_domains_given, args_info->allowed_domains_min, args_info->allowed_domains_max, "'--allowed-domains' ('-a')"))
     error_occurred = 1;
  
  if (check_multiple_option_occurrences(prog_name, args_info->disallowed_paths_given, args_info->disallowed_paths_min, args_info->disallowed_paths_max, "'--disallowed-paths' ('-d')"))
     error_occurred = 1;
  
  if (check_multiple_option_occurrences(prog_name, args_info->allowed_extensions_given, args_info->allowed_extensions_min, args_info->allowed_extensions_max, "'--allowed-extensions' ('-x')"))
     error_occurred = 1;
  
  
  /* checks for dependences among options */

  return error_occurred;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  FIX_UNUSED (default_value);
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}

/**
 * @brief store information about a multiple option in a temporary list
 * @param list where to (temporarily) store multiple options
 */
static
int update_multiple_arg_temp(struct generic_list **list,
               unsigned int *prev_given, const char *val,
               const char *possible_values[], const char *default_value,
               cmdline_parser_arg_type arg_type,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  /* store single arguments */
  char *multi_token;
  const char *multi_next;

  if (arg_type == ARG_NO) {
    (*prev_given)++;
    return 0; /* OK */
  }

  multi_token = get_multiple_arg_token(val);
  multi_next = get_multiple_arg_token_next (val);

  while (1)
    {
      add_node (list);
      if (update_arg((void *)&((*list)->arg), &((*list)->orig), 0,
          prev_given, multi_token, possible_values, default_value, 
          arg_type, 0, 1, 1, 1, long_opt, short_opt, additional_error)) {
        if (multi_token) free(multi_token);
        return 1; /* failure */
      }

      if (multi_next)
        {
          multi_token = get_multiple_arg_token(multi_next);
          multi_next = get_multiple_arg_token_next (multi_next);
        }
      else
        break;
    }

  return 0; /* OK */
}

/**
 * @brief free the passed list (including possible string argument)
 */
static
void free_list(struct generic_list *list, short string_arg)
{
  if (list) {
    struct generic_list *tmp;
    while (list)
      {
        tmp = list;
        if (string_arg && list->arg.string_arg)
          free (list->arg.string_arg);
        if (list->orig)
          free (list->orig);
        list = list->next;
        free (tmp);
      }
  }
}

/**
 * @brief updates a multiple option starting from the passed list
 */
static
void update_multiple_arg(void *field, char ***orig_field,
               unsigned int field_given, unsigned int prev_given, union generic_value *default_value,
               cmdline_parser_arg_type arg_type,
               struct generic_list *list)
{
  int i;
  struct generic_list *tmp;

  if (prev_given && list) {
    *orig_field = (char **) realloc (*orig_field, (field_given + prev_given) * sizeof (char *));

    switch(arg_type) {
    case ARG_INT:
      *((int **)field) = (int *)realloc (*((int **)field), (field_given + prev_given) * sizeof (int)); break;
    case ARG_STRING:
      *((char ***)field) = (char **)realloc (*((char ***)field), (field_given + prev_given) * sizeof (char *)); break;
    default:
      break;
    };
    
    for (i = (prev_given - 1); i >= 0; --i)
      {
        tmp = list;
        
        switch(arg_type) {
        case ARG_INT:
          (*((int **)field))[i + field_given] = tmp->arg.int_arg; break;
        case ARG_STRING:
          (*((char ***)field))[i + field_given] = tmp->arg.string_arg; break;
        default:
          break;
        }        
        (*orig_field) [i + field_given] = list->orig;
        list = list->next;
        free (tmp);
      }
  } else { /* set the default value */
    if (default_value && ! field_given) {
      switch(arg_type) {
      case ARG_INT:
        if (! *((int **)field)) {
          *((int **)field) = (int *)malloc (sizeof (int));
          (*((int **)field))[0] = default_value->int_arg; 
        }
        break;
      case ARG_STRING:
        if (! *((char ***)field)) {
          *((char ***)field) = (char **)malloc (sizeof (char *));
          (*((char ***)field))[0] = gengetopt_strdup(default_value->string_arg);
        }
        break;
      default: break;
      }
      if (!(*orig_field)) {
        *orig_field = (char **) malloc (sizeof (char *));
        (*orig_field)[0] = 0;
      }
    }
  }
}

int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  struct generic_list * allowed_domains_list = NULL;
  struct generic_list * disallowed_paths_list = NULL;
  struct generic_list * allowed_extensions_list = NULL;
  int error_occurred = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  /* TODO: Why is this here? It is not used anywhere. */
  override = params->override;
  FIX_UNUSED(override);

  initialize = params->initialize;
  check_required = params->check_required;

  /* TODO: Why is this here? It is not used anywhere. */
  check_ambiguity = params->check_ambiguity;
  FIX_UNUSED(check_ambiguity);

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "threads",	1, NULL, 't' },
        { "url",	1, NULL, 'u' },
        { "timeout",	1, NULL, 'm' },
        { "max-depth",	1, NULL, 'D' },
        { "allow-subdomains",	0, NULL, 's' },
        { "allowed-domains",	1, NULL, 'a' },
        { "disallowed-paths",	1, NULL, 'd' },
        { "allowed-extensions",	1, NULL, 'x' },
        { "keep-query",	0, NULL, 'k' },
        { "no-color",	0, NULL, 'c' },
        { "user-agent",	1, NULL, 'U' },
        { "title",	0, NULL, 'T' },
        { "sitemap",	1, NULL, 'S' },
        { "http-only",	0, NULL, 'p' },
        { "https-only",	0, NULL, 'P' },
        { "only-body",	0, NULL, 'B' },
        { "only-head",	0, NULL, 'H' },
        { "IPv6",	0, NULL, '6' },
        { "IPv4",	0, NULL, '4' },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVt:u:m:D:sa:d:x:kcU:TS:pPBH64", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 't':	/* Number of threads..  */
        
        
          if (update_arg( (void *)&(args_info->threads_arg), 
               &(args_info->threads_orig), &(args_info->threads_given),
              &(local_args_info.threads_given), optarg, 0, "5", ARG_INT,
              check_ambiguity, override, 0, 0,
              "threads", 't',
              additional_error))
            goto failure;
        
          break;
        case 'u':	/* URL of where to start..  */
        
        
          if (update_arg( (void *)&(args_info->url_arg), 
               &(args_info->url_orig), &(args_info->url_given),
              &(local_args_info.url_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "url", 'u',
              additional_error))
            goto failure;
        
          break;
        case 'm':	/* Timeout in seconds..  */
        
        
          if (update_arg( (void *)&(args_info->timeout_arg), 
               &(args_info->timeout_orig), &(args_info->timeout_given),
              &(local_args_info.timeout_given), optarg, 0, "3", ARG_INT,
              check_ambiguity, override, 0, 0,
              "timeout", 'm',
              additional_error))
            goto failure;
        
          break;
        case 'D':	/* Maximum depth of paths..  */
        
        
          if (update_arg( (void *)&(args_info->max_depth_arg), 
               &(args_info->max_depth_orig), &(args_info->max_depth_given),
              &(local_args_info.max_depth_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "max-depth", 'D',
              additional_error))
            goto failure;
        
          break;
        case 's':	/* Allow the crawler to go to URLs found on a sub-domain..  */
        
        
          if (update_arg((void *)&(args_info->allow_subdomains_flag), 0, &(args_info->allow_subdomains_given),
              &(local_args_info.allow_subdomains_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "allow-subdomains", 's',
              additional_error))
            goto failure;
        
          break;
        case 'a':	/* Allow the crawler to go to URLs found on other domains..  */
        
          if (update_multiple_arg_temp(&allowed_domains_list, 
              &(local_args_info.allowed_domains_given), optarg, 0, 0, ARG_STRING,
              "allowed-domains", 'a',
              additional_error))
            goto failure;
        
          break;
        case 'd':	/* Disallow the crawler to go to these directories..  */
        
          if (update_multiple_arg_temp(&disallowed_paths_list, 
              &(local_args_info.disallowed_paths_given), optarg, 0, 0, ARG_STRING,
              "disallowed-paths", 'd',
              additional_error))
            goto failure;
        
          break;
        case 'x':	/* The crawler will only fetch documents with these extensions, but if no extension is found in an URL, this filter won't apply. Extensions have to start with a '.' (dot)..  */
        
          if (update_multiple_arg_temp(&allowed_extensions_list, 
              &(local_args_info.allowed_extensions_given), optarg, 0, 0, ARG_STRING,
              "allowed-extensions", 'x',
              additional_error))
            goto failure;
        
          break;
        case 'k':	/* Keep the query part in the URL..  */
        
        
          if (update_arg((void *)&(args_info->keep_query_flag), 0, &(args_info->keep_query_given),
              &(local_args_info.keep_query_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "keep-query", 'k',
              additional_error))
            goto failure;
        
          break;
        case 'c':	/* Don't use color when outputing on the console..  */
        
        
          if (update_arg((void *)&(args_info->no_color_flag), 0, &(args_info->no_color_given),
              &(local_args_info.no_color_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "no-color", 'c',
              additional_error))
            goto failure;
        
          break;
        case 'U':	/* Set the user-agent string. You can not send the user-agent header by giving an empty string..  */
        
        
          if (update_arg( (void *)&(args_info->user_agent_arg), 
               &(args_info->user_agent_orig), &(args_info->user_agent_given),
              &(local_args_info.user_agent_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "user-agent", 'U',
              additional_error))
            goto failure;
        
          break;
        case 'T':	/* Print title if there is one..  */
        
        
          if (update_arg((void *)&(args_info->title_flag), 0, &(args_info->title_given),
              &(local_args_info.title_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "title", 'T',
              additional_error))
            goto failure;
        
          break;
        case 'S':	/* URL of the sitemap..  */
        
        
          if (update_arg( (void *)&(args_info->sitemap_arg), 
               &(args_info->sitemap_orig), &(args_info->sitemap_given),
              &(local_args_info.sitemap_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "sitemap", 'S',
              additional_error))
            goto failure;
        
          break;
        case 'p':	/* Only fetch URLs with HTTP as scheme..  */
        
          if (args_info->scheme_group_counter && override)
            reset_group_scheme (args_info);
          args_info->scheme_group_counter += 1;
        
          if (update_arg( 0 , 
               0 , &(args_info->http_only_given),
              &(local_args_info.http_only_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "http-only", 'p',
              additional_error))
            goto failure;
        
          break;
        case 'P':	/* Only fetch URLs with HTTPS as scheme..  */
        
          if (args_info->scheme_group_counter && override)
            reset_group_scheme (args_info);
          args_info->scheme_group_counter += 1;
        
          if (update_arg( 0 , 
               0 , &(args_info->https_only_given),
              &(local_args_info.https_only_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "https-only", 'P',
              additional_error))
            goto failure;
        
          break;
        case 'B':	/* Only parse the <body>..  */
        
          if (args_info->parsing_part_group_counter && override)
            reset_group_parsing_part (args_info);
          args_info->parsing_part_group_counter += 1;
        
          if (update_arg( 0 , 
               0 , &(args_info->only_body_given),
              &(local_args_info.only_body_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "only-body", 'B',
              additional_error))
            goto failure;
        
          break;
        case 'H':	/* Only parse the <head>..  */
        
          if (args_info->parsing_part_group_counter && override)
            reset_group_parsing_part (args_info);
          args_info->parsing_part_group_counter += 1;
        
          if (update_arg( 0 , 
               0 , &(args_info->only_head_given),
              &(local_args_info.only_head_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "only-head", 'H',
              additional_error))
            goto failure;
        
          break;
        case '6':	/* Only resolve to IPv6 addresses..  */
        
          if (args_info->resolving_ip_version_group_counter && override)
            reset_group_resolving_ip_version (args_info);
          args_info->resolving_ip_version_group_counter += 1;
        
          if (update_arg( 0 , 
               0 , &(args_info->IPv6_given),
              &(local_args_info.IPv6_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "IPv6", '6',
              additional_error))
            goto failure;
        
          break;
        case '4':	/* Only resolve to IPv4 addresses..  */
        
          if (args_info->resolving_ip_version_group_counter && override)
            reset_group_resolving_ip_version (args_info);
          args_info->resolving_ip_version_group_counter += 1;
        
          if (update_arg( 0 , 
               0 , &(args_info->IPv4_given),
              &(local_args_info.IPv4_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "IPv4", '4',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */

  if (args_info->parsing_part_group_counter > 1)
    {
      fprintf (stderr, "%s: %d options of group parsing-part were given. At most one is required%s.\n", argv[0], args_info->parsing_part_group_counter, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  
  if (args_info->resolving_ip_version_group_counter > 1)
    {
      fprintf (stderr, "%s: %d options of group resolving-ip-version were given. At most one is required%s.\n", argv[0], args_info->resolving_ip_version_group_counter, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  
  if (args_info->scheme_group_counter > 1)
    {
      fprintf (stderr, "%s: %d options of group scheme were given. At most one is required%s.\n", argv[0], args_info->scheme_group_counter, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  

  update_multiple_arg((void *)&(args_info->allowed_domains_arg),
    &(args_info->allowed_domains_orig), args_info->allowed_domains_given,
    local_args_info.allowed_domains_given, 0,
    ARG_STRING, allowed_domains_list);
  update_multiple_arg((void *)&(args_info->disallowed_paths_arg),
    &(args_info->disallowed_paths_orig), args_info->disallowed_paths_given,
    local_args_info.disallowed_paths_given, 0,
    ARG_STRING, disallowed_paths_list);
  update_multiple_arg((void *)&(args_info->allowed_extensions_arg),
    &(args_info->allowed_extensions_orig), args_info->allowed_extensions_given,
    local_args_info.allowed_extensions_given, 0,
    ARG_STRING, allowed_extensions_list);

  args_info->allowed_domains_given += local_args_info.allowed_domains_given;
  local_args_info.allowed_domains_given = 0;
  args_info->disallowed_paths_given += local_args_info.disallowed_paths_given;
  local_args_info.disallowed_paths_given = 0;
  args_info->allowed_extensions_given += local_args_info.allowed_extensions_given;
  local_args_info.allowed_extensions_given = 0;
  
  if (check_required)
    {
      error_occurred += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error_occurred )
    return (EXIT_FAILURE);

  return 0;

failure:
  free_list (allowed_domains_list, 1 );
  free_list (disallowed_paths_list, 1 );
  free_list (allowed_extensions_list, 1 );
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
/* vim: set ft=c noet ts=8 sts=8 sw=8 tw=80 nojs spell : */
